server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://10.10.1.156:3306/mysql
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  rabbitmq:
    host: 10.10.1.156
    username: guest
    password: guest
    virtual-host: /zt
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 300000ms
        multiplier: 2
      exchange: zt.item.exchange
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://10.10.1.156:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true # 返回eureka的是ip，而不是主机名
    ip-address: 10.10.1.156 # 设置返回的ip是啥
    instance-id: ${spring.application.name}:${server.port}
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




