#定义端口号
server:
  port: 8201

#定义服务名称
spring:
  application:
    name: zt-gateway
#配置注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

#自定义路由转发：
zuul:
  routes:

zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    # 微服务名: 要映射到到地址
    item-service:
      path: /item/** # 将商品微服务映射到/item/**
      serviceId: item-service
    search-service:
      path: /search/** # 将查询微服务映射到/search/**
      serviceId: search-service
    upload-service:
      path: /upload/** # 将上传微服务映射到/upload/**
      serviceId: upload-service
      strip-prefix : false
    #将order-service服务路由自定义为apigateway-order
    #原访问地址：http://localhost:9000/order-service/getProductInfoById?id=2
    #也可以这样: http://localhost:9000/apigateway-order/getProductInfoById?id=2
    order-service: /apigateway-order/**
    product-service: /apigateway-product/**
  #环境隔离配置：不对外提供order-service访问
  #配置后：原访问地址：http://localhost:9000/order-service/getProductInfoById?id=2 将不能在访问
  ignored-patterns: /*-service/**
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
