server:
  port: 8888
spring:
  application:
    name: config-service
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ztbxufei/ztbConfig.git #配置git仓库地址
          searchPaths: /config #配置仓库路径
          username: ssaorry    #访问git仓库的用户名
          password: jingfei183 #访问git仓库的用户密码
      label: master #配置仓库的分支
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      prefer-ip-address: true
      hostname: ${spring.cloud.client.ip-address}
      instanceId: ${spring.cloud.client.ip-address}:${server.port}

