server:
  port: 8761

spring:
  application:
    name: eureka-service

eureka:
  server:
    # 是否开启自我保护，默认为 true，在开启自我保护的情况下，注册中心在丢失客户端时，会进入自动保护模式，
    # 注册中心并不会将该服务从注册中心删除掉。这里我设置为 false，即关闭自我保护。如果设置为true，
    # 在负载均衡条件下，一个服务挂掉后，注册中心并没有删掉该服务，会导致客户端请求的时候可能会请求到该服务，
    # 导致系统无法访问，所以推荐将这个属性设置为 false。
    enable-self-preservation: false
  instance:
    prefer-ip-address: true # 是否以ip注册到服务中心
    hostname: ${spring.cloud.client.ip-address} # 主机ip
    instanceId: ${spring.cloud.client.ip-address}:${server.port} # ip:port
  client:
    # 通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      # 注册中心默认地址。
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


