
server:
  port: 8001

#配置服务注册地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#指定服务名称
spring:
  application:
    name: order-service
  #配置redis仓库地址（当前配置为本机）
  redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: 12345
      timeout: 2000

#自定义负载均衡策略
#策略选择：
#    1、如果每个机器配置一样，则建议不修改策略 (推荐)
#    2、如果部分机器配置强，则可以改为 WeightedResponseTimeRule
product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  #随机策略



feign:
  hystrix:
    enabled: true   # 开启feign支持hystrix
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000   #设置服务调用超时时间 默认optons readtimeout是60，但是由于hystrix默认是1秒超时